language: bash
sudo: required
services:
  - docker
env:
  global:
    - CONTAINER_IMAGE_1=gdal
    - CONTAINER_IMAGE_2=grass
    - CONTAINER_IMAGE_3=postgresql
    - CONTAINER_IMAGE_4=r

jobs:
  include:
    - stage: 'Primary images'

      script: sudo bash /stage_1_primary_images/script/script_gdal.sh
      script: sudo bash /stage_1_primary_images/script/script_grass.sh
      script: sudo bash /stage_1_primary_images/script/script_postgresql.sh
      script: sudo bash /stage_1_primary_images/script/script_r.sh
