language: bash
sudo: required
services:
  - docker

defaults: &defaults
  before_script:
    - export BUILD_DATE=$(date '+%d/%m/%Y %T UTC' -u)
    - docker pull $USERNAME/$IMAGE_NAME:latest || true

  script:
    - docker build --cache-from $USERNAME/$IMAGE_NAME:latest --build-arg BUILD_DATE="${BUILD_DATE}" --build-arg TRAVIS_COMMIT="${TRAVIS_COMMIT}" --tag $USERNAME/$IMAGE_NAME:$TRAVIS_COMMIT --tag $USERNAME/$IMAGE_NAME:latest -f $DOCKERFILE .

  after_script:
    - docker images

  before_deploy:
    - echo $PASSWORD | docker login docker.io -u $USERNAME --password-stdin

  deploy:
    provider: script
    script:
      - docker push $USERNAME/$IMAGE_NAME:$TRAVIS_COMMIT && docker push $USERNAME/$IMAGE_NAME:latest
    on:
      branch: master

  after_deploy:
    - bash sh post_script.sh

jobs:
  include:
    - stage: Build Primary Images
      env:
        - IMAGE_NAME=tomcat-r
        - DOCKERFILE=stage_1_primary_images/r.dockerfile
        - LINK_BADGER=https://hooks.microbadger.com/images/autimio/tomcat-r/inwV-kTlqCkxV6WFWesIGRh-cWo=
      <<: *defaults
    - 
      env:
        - IMAGE_NAME=tomcat-gdal
        - DOCKERFILE=stage_1_primary_images/gdal.dockerfile
        - LINK_BADGER=https://hooks.microbadger.com/images/autimio/tomcat-gdal/z5hoezHBR5xvReNMYl0iH3H50mA=
      <<: *defaults
    - 
      env:
        - IMAGE_NAME=tomcat-grass
        - DOCKERFILE=stage_1_primary_images/grass.dockerfile
        - LINK_BADGER=https://hooks.microbadger.com/images/autimio/tomcat-grass/D8v8B4fyb_gjaHH06xGkEBNwbEY=
      <<: *defaults
    - 
      env:
        - IMAGE_NAME=tomcat-postgresql
        - DOCKERFILE=stage_1_primary_images/postgresql.dockerfile
        - LINK_BADGER=https://hooks.microbadger.com/images/autimio/tomcat-postgresql/p646B2SYb4WqzhF_NY3i5-5vnAU=
      <<: *defaults
