language: bash
sudo: required
services:
  - docker

defaults: &defaults
  before_script:
    - export BUILD_DATE=$(date '+%d/%m/%Y %T UTC' -u)
    - docker pull $USERNAME/$IMAGE_NAME:latest || true

  script:
    - docker build --cache-from $USERNAME/$IMAGE_NAME:latest --build-arg BUILD_DATE="${BUILD_DATE}" --build-arg TRAVIS_COMMIT="${TRAVIS_COMMIT}" --tag $USERNAME/$IMAGE_NAME:$TRAVIS_COMMIT --tag $USERNAME/$IMAGE_NAME:latest -f $DOCKERFILE .

  after_script:
    - docker images

  before_deploy:
    - echo $PASSWORD | docker login -u $USERNAME --password-stdin

  deploy:
    provider: script
    script:
      - docker tag latest $USERNAME/$IMAGE_NAME 
      - docker push $USERNAME/$IMAGE_NAME:$TRAVIS_COMMIT && docker push $USERNAME/$IMAGE_NAME:latest
    on:
      branch: master

  after_deploy:
    - curl --header "Content-Type: application/json" --request POST --data '{}' https://hooks.microbadger.com/images/autimio/postgis/hash

jobs:
  include:
    - stage: test
      env:
        - IMAGE_NAME=r
        - DOCKERFILE=stage_1_primary_images/r.dockerfile
      <<: *defaults
    - stage: test
      env:
        - IMAGE_NAME=gdal
        - DOCKERFILE=stage_1_primary_images/gdal.dockerfile
      <<: *defaults
    - stage: test
      env:
        - IMAGE_NAME=grass
        - DOCKERFILE=stage_1_primary_images/grass.dockerfile
      <<: *defaults
    - stage: test
      env:
        - IMAGE_NAME=postgres
        - DOCKERFILE=stage_1_primary_images/postgres.dockerfile
      <<: *defaults
